# Reference https://github.com/pydata/xarray/blob/main/pyproject.toml
[build-system]
requires = [
    "setuptools>=59",
    "setuptools_scm[toml]>=6.4",
    "wheel",
]
build-backend = "setuptools.build_meta"

# pytest
[tool.pytest.ini_options]
testpaths = [
    "tests"
]
addopts = "--pyargs --cov=gnuplot_kernel --cov-report=xml --import-mode=importlib"

[tool.setuptools_scm]
fallback_version = "999"
version_scheme = 'post-release'
