name: build

on: [push, pull_request]

jobs:
  # Unittests
  unittests:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        python-version: ["3.8", "3.10"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Packages
        shell: bash -l {0}
        run: |
          sudo apt-get install gnuplot
          pip install -e ".[test]"
          pip install coveralls

      - name: Environment Information
        shell: bash -l {0}
        run: |
          gnuplot --version
          pip list

      - name: Run Tests
        shell: bash -l {0}
        run: |
          coverage erase
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          name: "py${{ matrix.python-version }}"

  # Linting
  lint:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Packages
        shell: bash -l {0}
        run: pip install flake8

      - name: Environment Information
        shell: bash -l {0}
        run: pip list

      - name: Run Tests
        shell: bash -l {0}
        run: make lint
